"""Add bio column to User table

Revision ID: 05596f3b9273
Revises: 
Create Date: 2023-07-26 21:32:33.484424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05596f3b9273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.drop_column('profilePhoto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilePhoto', sa.BLOB(), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
