"""Add profile photo column to User table

Revision ID: 83da635ce19b
Revises: 05596f3b9273
Create Date: 2023-07-26 21:40:20.690572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83da635ce19b'
down_revision = '05596f3b9273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilePhotoLink', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profilePhotoLink')

    # ### end Alembic commands ###
