"""transaction table

Revision ID: 1667f7dd0939
Revises: 9fca9afda70e
Create Date: 2023-08-04 19:20:02.189169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1667f7dd0939'
down_revision = '9fca9afda70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('artwork_name')
        batch_op.drop_column('seller_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_name', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('artwork_name', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
