"""empty message

Revision ID: 398d513d10b7
Revises: f8e1d2c1b271
Create Date: 2023-07-31 04:34:16.411044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398d513d10b7'
down_revision = 'f8e1d2c1b271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploadDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('uploadDate')

    # ### end Alembic commands ###
