"""empty message

Revision ID: 5d8fb7cc0c72
Revises: 398d513d10b7
Create Date: 2023-08-02 18:27:27.082436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8fb7cc0c72'
down_revision = '398d513d10b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('artist')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
