"""Added shop_item to artwork model

Revision ID: 9fca9afda70e
Revises: 0d14636ce3dd
Create Date: 2023-08-03 13:08:27.236487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fca9afda70e'
down_revision = '0d14636ce3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('shop_item', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'shop_item')
    # ### end Alembic commands ###
