"""empty message

Revision ID: c8df5791a399
Revises: 6227d89730ea
Create Date: 2023-08-02 22:48:22.426841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8df5791a399'
down_revision = '6227d89730ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('shop_item', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'shop_item')
    # ### end Alembic commands ###
